documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**

readme:
  - changed-files:
      - any-glob-to-any-file: README.md

prod:
  - changed-files:
      - any-glob-to-any-file: PROD/**

sandbox:
  - changed-files:
      - any-glob-to-any-file: SANDBOX/**

feature:
  - head-branch: ['^feature', '^feat']

fix:
  - head-branch: ['^fix']
