# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
Documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**

README:
  - changed-files:
      - any-glob-to-any-file: README.md

PROD:
  - changed-files:
      - any-glob-to-any-file: PROD/**

SANDBOX:
  - changed-files:
      - any-glob-to-any-file: SANDBOX/**

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
  - head-branch: ['^feature', '^feat']

fix:
  - head-branch: ['^fix']